# Generated by Django 3.0.4 on 2020-03-24 15:40

from django.db import migrations, models
import django.db.models.deletion


# Migração Inicial do Django com base nos modelos para criação das tabelas no banco e seus relacionamentos
class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id_guest', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=False, max_length=11, null=False)),
            ],
            options={
                'db_table': 'tb_guests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id_qrcode', models.AutoField(primary_key=True, serialize=False)),
                ('qrcode_content', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'tb_qrcode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QrCodeGuest',
            fields=[
                ('id_qrcode_guest', models.AutoField(primary_key=True, serialize=False)),
                ('id_guest_ext', models.ForeignKey(db_column='id_guest_ext', on_delete=django.db.models.deletion.CASCADE, to='polls.Guests', unique=True)),
                ('id_qrcode_ext', models.ForeignKey(db_column='id_qrcode_ext', on_delete=django.db.models.deletion.CASCADE, to='polls.Qrcode')),
            ],
            options={
                'db_table': 'tb_qrcode_guest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Accredited',
            fields=[
                ('id_accredited', models.AutoField(primary_key=True, serialize=False)),
                ('id_guest_acc_ext', models.ForeignKey(db_column='id_guest_acc_ext', on_delete=django.db.models.deletion.CASCADE, to='polls.Guests')),
                ('accredited', models.BooleanField(default=False))
            ],
            options={
                'db_table': 'tb_accredited',
                'managed': True,
            },
        )
    ]

